# Generated by Django 5.0.6 on 2024-06-28 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBatchResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_id', models.CharField(max_length=100)),
                ('batch_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('extraction_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileId', models.CharField(max_length=100)),
                ('fileName', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('total_price', models.CharField(max_length=255)),
                ('unit_price', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_address', models.CharField(max_length=255)),
                ('merchant_name', models.CharField(max_length=255)),
                ('merchant_tax_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('extraction_id', models.CharField(max_length=100)),
                ('batch_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extractionId', models.CharField(max_length=255)),
                ('batchId', models.CharField(max_length=255)),
                ('files', models.ManyToManyField(to='imagetotextapp.file')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_date', models.DateField()),
                ('receipt_id', models.CharField(max_length=100)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items', models.ManyToManyField(to='imagetotextapp.item')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagetotextapp.merchant')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imagetotextapp.result'),
        ),
    ]
