# Generated by Django 5.0.6 on 2025-01-24 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetotextapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imagetotextapp.merchant'),
        ),
    ]
