# Generated by Django 5.0.6 on 2024-06-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetotextapp', '0002_alter_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Everything',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
    ]
