# Generated by Django 5.0.6 on 2025-05-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagetotextapp", "0002_alter_extraction_merchant"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraction",
            name="batch_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="extraction",
            name="extraction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
