# Generated by Django 5.0.6 on 2025-05-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagetotextapp", "0003_extraction_batch_id_extraction_extraction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionitem",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
