# Generated by Django 5.0.6 on 2024-06-29 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetotextapp', '0003_everything'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='json_responses', to='imagetotextapp.extraction')),
            ],
        ),
        migrations.DeleteModel(
            name='Everything',
        ),
    ]
