# Generated by Django 5.0.6 on 2024-07-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagetotextapp', '0004_jsonresponse_delete_everything'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JsonResponse',
        ),
    ]
